<a href="https://colab.research.google.com/github/CarlstonG/Cakeandsweets/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# in this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensoflow 

More specifically, we're going to cover"
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensos & Numpy
* using @tf.function (a way to speed up your regular python functions)
* Using GPUS with tensorflow
*exercises to try for yourself!

Introduction to Tensor

In [1]:
# import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stand for number of dimensions)

In [4]:
scalar.ndim

0

In [ ]:
# Create a vector

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector

In [6]:
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)

In [7]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [ ]:
# Create another matrix 

In [9]:
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor 


In [12]:
tensor = tf.constant([[[1, 2, 3,], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

What we've Created so far:
* Scalar: a single number
* Vector: a number with direction (e. g. wind, speed, direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, 0-dimensional tensor is a scalar, a 1-dimensional tensor is vector) 

In [ ]:
### Creating tensors with tf.Variable


In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
# Create tge sane tensor with tf.Variable as above

In [16]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Assign new value to changeable tensor

In [20]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>